//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public string idProducto { get; set; }
        public string nombreProducto { get; set; }
        public string descripcion { get; set; }
        public string ingredientes { get; set; }
        public string administracion { get; set; }
        public string precauciones { get; set; }
        public string contraindicaciones { get; set; }
        public string img { get; set; }
    }
}
